# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_add_default_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreathingProtectionTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=100, verbose_name='Date')),
                ('location', models.CharField(blank=True, max_length=20, null=True, verbose_name='Location')),
                ('creation_date', models.DateTimeField(blank=True, null=True, verbose_name='Creation date')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Last update')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.UserProfile', verbose_name='Editor')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpt_organizer', to='base.UserProfile', verbose_name='Organizer')),
                ('participants', models.ManyToManyField(blank=True, related_name='bpt_participants', to='base.UserProfile', verbose_name='Participants')),
            ],
            options={
                'ordering': ('-date',),
                'verbose_name': 'Breathing Protection Training',
                'verbose_name_plural': 'Breathing Protection Trainings',
                'permissions': (('view_breathingprotectiontraining', 'Can view breathing protection trainings'),),
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Number')),
                ('alarm_time', models.DateTimeField(verbose_name='Alarm Time')),
                ('keyword', models.CharField(db_index=True, max_length=100, verbose_name='Keyword')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('volume', models.CharField(blank=True, max_length=100, null=True, verbose_name='Volume')),
                ('concerned', models.CharField(blank=True, max_length=20, null=True, verbose_name='Concerned')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('street', models.CharField(max_length=200, verbose_name='Street')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('coordinates', djgeojson.fields.PointField(blank=True, null=True, verbose_name='Coordinates')),
                ('signal', models.BooleanField(default=True, verbose_name='Signal')),
                ('creation_date', models.DateTimeField(blank=True, null=True, verbose_name='Creation date')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Last update')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission_editor', to='base.UserProfile', verbose_name='Editor')),
                ('firefighters', models.ManyToManyField(blank=True, related_name='mission_firefighters', to='base.UserProfile', verbose_name='Firefighters')),
                ('vehicles', models.ManyToManyField(blank=True, to='base.Vehicle', verbose_name='Vehicles')),
            ],
            options={
                'ordering': ('-alarm_time',),
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'permissions': (('view_mission', 'Can view missions'),),
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=100, verbose_name='Date')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Note')),
                ('creation_date', models.DateTimeField(blank=True, null=True, verbose_name='Creation date')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Last update')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_editor', to='base.UserProfile', verbose_name='Editor')),
                ('responsibles', models.ManyToManyField(blank=True, related_name='training_responsibles', to='base.UserProfile', verbose_name='Responsibles')),
            ],
            options={
                'ordering': ('-date',),
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
                'permissions': (('view_training', 'Can view trainings'),),
            },
        ),
    ]
