# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Number')),
                ('alarm_time', models.DateTimeField(verbose_name='Alarm Time')),
                ('keyword', models.CharField(db_index=True, max_length=100, verbose_name='Keyword')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('volume', models.CharField(blank=True, max_length=100, null=True, verbose_name='Volume')),
                ('concerned', models.CharField(blank=True, max_length=20, null=True, verbose_name='Concerned')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('street', models.CharField(max_length=200, verbose_name='Street')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('coordinates', djgeojson.fields.PointField(blank=True, null=True, verbose_name='Coordinates')),
                ('signal', models.BooleanField(default=True, verbose_name='Signal')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
            },
        ),
    ]
