# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_adding_fixtures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firehouse',
            options={'ordering': ('name',), 'verbose_name': 'Fire House', 'verbose_name_plural': 'Fire Houses'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-creation_date',), 'permissions': (('view_message', 'Can view messages'),), 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ('name',), 'verbose_name': 'Municipality', 'verbose_name_plural': 'Municipalities'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('user__last_name',), 'permissions': (('view_breathingprotectioncarrier', 'Can view breathing protection carriers'), ('change_breathingprotectioncarrier', 'Can change breathing protection carrier')), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ('call_sign',), 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
    ]
