# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_adding_fixtures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='admittance',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='admittance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Admittance Date'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='breathing_protection_carrier',
            field=models.BooleanField(default=False, verbose_name='Breathing Protection Carrier'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='next_breathing_protection_training_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next Breathing Protection Training Date'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='next_medical_examination_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next Medical Examination Date'),
        ),
    ]
