# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 07:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_add_model_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Grade')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone Number')),
                ('mobile_phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Mobile Phone Number')),
                ('birth_date', models.DateField(blank=True, max_length=45, null=True, verbose_name='Birth Date')),
                ('online', models.BooleanField(default=False, verbose_name='Online')),
                ('online_date', models.DateTimeField(blank=True, null=True, verbose_name='Online date')),
                ('online_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='Online IP')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user',
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
