# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_add_model_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='firefighters',
            field=models.ManyToManyField(to='base.UserProfile'),
        ),
    ]
