# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_add_field_mission_firefighters'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreathingProtectionTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=100, verbose_name='Date')),
                ('location', models.CharField(blank=True, max_length=20, null=True, verbose_name='Location')),
                ('firefighters', models.ManyToManyField(related_name='bpt_firefighters', to='base.UserProfile', verbose_name='Firefighters')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpt_organizer', to='base.UserProfile', verbose_name='Organizer')),
            ],
            options={
                'verbose_name': 'Breathing Protection Training',
                'verbose_name_plural': 'Breathing Protection Trainings',
            },
        ),
    ]
