# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_add_model_breathingprotectiontraining'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=100, verbose_name='Date')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('hint', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hint')),
                ('firefighters', models.ManyToManyField(to='base.UserProfile', verbose_name=b'Firefighters')),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
            },
        ),
    ]
